### PR TITLE
Update library to support latest versions of Rust and Windows

### PR DESCRIPTION
**Pull request by raybritton**
The text changes may only be correct for some versions of Windows, I only have the latest version of Windows 10 to test with. 
This does also fix https://github.com/TNkemdilim/wifi-rs/issues/3

### CODE REVIEW

**Comment by dzcpy** [comment]
Will this be merged soon? I really need to get it work on Windows..

**Comment by TNkemdilim** [comment]
Hello @dzcpy ,

Apologies for the delayed response.

I'll be merging this then.

**Comment by TNkemdilim** [comment]
@dzcpy 

I just published a new version `0.2.1`.

**Comment by dzcpy** [comment]
@TNkemdilim Thanks very much!

**Pull request merged**
